"""Deprecated compatibility facade for contracts now owned by ``execution``."""

from control.domain import (
    ControlOperationResult,
    ControlOperationStatus,
    DevicePoint,
    Key,
    KeyChord,
    KeyDown,
    KeyPress,
    KeyUp,
    PointerButton,
    PointerClick,
    PointerDrag,
    PointerMove,
    PointerScroll,
    ScreenPoint,
    ScrollDelta,
    TextEntry,
    WindowActivation,
    WindowRestore,
)
from control.ports import (
    BackNavigator,
    KeyChordController,
    KeyPresser,
    KeyStateController,
    PointerClicker,
    PointerDragger,
    PointerMover,
    PointerScroller,
    TextController,
    WindowActivator,
    WindowRestorer,
)

__all__ = [
    "BackNavigator",
    "ControlOperationResult",
    "ControlOperationStatus",
    "DevicePoint",
    "Key",
    "KeyChord",
    "KeyChordController",
    "KeyDown",
    "KeyPress",
    "KeyPresser",
    "KeyStateController",
    "KeyUp",
    "PointerButton",
    "PointerClick",
    "PointerClicker",
    "PointerDrag",
    "PointerDragger",
    "PointerMove",
    "PointerMover",
    "PointerScroll",
    "PointerScroller",
    "ScreenPoint",
    "ScrollDelta",
    "TextController",
    "TextEntry",
    "WindowActivation",
    "WindowActivator",
    "WindowRestore",
    "WindowRestorer",
]
